var urlHost = 'https://raw.githubusercontent.com/Sturm1212/vtt_spell_icons/main/';


function updateSpellList() {
    for(var i = 0; i < spellList.length; i++) {
        console.log('test');
        var SpellName = spellList[i][0];
        
        var SpellNameCustom = spellList[i][0] + '!';
        if(spellList[i][1].length){
            var IconID = spellList[i][1];
        }else{
            var IconID = spellList[i][0].replaceAll(' ', '_');
        }

        var SpellLevel = spellList[i][2];
        
        if($('.spells').length > 0){ 
            if ( $('.spellname:contains("'+SpellName+'")')[0] ) { 
                $('.spellname:contains("'+SpellName+'")').filter((i, p) => $(p).html() === SpellName).prepend('<img class="iconSpellSheet" width="32" src="'+urlHost+IconID+'.png"><img class="iconSpellRaritySheet" width="24" src="'+urlHost+'Level'+SpellLevel+'.png">');
                $('.spellname:contains("'+SpellNameCustom+'")').filter((i, p) => $(p).html() === SpellNameCustom).prepend('<img class="iconSpellSheet" width="32" src="'+urlHost+IconID+'.png"><img class="iconSpellRaritySheet" width="24" src="'+urlHost+'Level'+SpellLevel+'.png">');
            }
            if ( $('span:contains("'+SpellName+'")')[0] ) { 
                $('span:contains("'+SpellName+'")').filter((i, p) => $(p).html() === SpellName).prepend('<img class="iconSpellSheet" width="32" src="'+urlHost+IconID+'.png">');
                $('span:contains("'+SpellNameCustom+'")').filter((i, p) => $(p).html() === SpellNameCustom).prepend('<img class="iconSpellSheet" width="32" src="'+urlHost+IconID+'.png">');
            }
        }

        if($("#compendiumtab").hasClass("ui-state-active")){ 
            if ( $('.namecontainer:contains("'+SpellName+'")')[0] ) { 
                $('.namecontainer:contains("'+SpellName+'")').filter((i, p) => $(p).html() === SpellName).prepend('<img class="iconSpellComp" width="40" src="'+urlHost+IconID+'.png"><img class="iconSpellRarity" width="40" src="'+urlHost+'Level'+SpellLevel+'.png">');
            }
        }
    }

    document.querySelectorAll('.iconSpellComp').forEach(function(img){
        img.onerror = function(){this.src='https://raw.githubusercontent.com/Sturm1212/vtt_spell_icons/main/default_bw.png';};
    });

    document.querySelectorAll('.iconSpellSheet').forEach(function(img){
        img.onerror = function(){this.src='https://raw.githubusercontent.com/Sturm1212/vtt_spell_icons/main/default_bw.png';};
    });

    $("input[name='attr_atkbonus']").css("height", "100%");
    $("input[name='attr_atkdmgtype']").css("height", "100%");
    
};

var intervalId = window.setInterval(function(){
    if($("#compendiumtab").hasClass("ui-state-active") || $('.spells').length > 0){ 
        updateSpellList();
    }
}, 5000);


var spellList = [
    ["Abhorrence", "", 0],
    ["Abhorrent Apparition", "", 4],
    ["Abi-Dalzim’s Horrid Wilting", "Abi-Dalzims-Horrid-Wilting", 8],
    ["Absorb Elements", "", 1],
    ["Absorbing Field", "", 6],
    ["Acid Splash", "", 0],
    ["Acumen", "", 0],
    ["Ale-Dritch Blast", "", 0],
    ["Allure", "Allure", 0],
    ["Animated Scroll", "", 0],
    ["Benediction", "", 0],
    ["Bewilderment", "", 0],
    ["Biting Arrow", "", 0],
    ["Black Goat's Blessing", "Black_Goat_Blessing", 0],
    ["Blade Ward", "", 0],
    ["Bless The Dead", "", 0],
    ["Blood Tide", "", 0],
    ["Booming Blade", "", 0],
    ["Brawn Boost", "", 0],
    ["Brimstone Infusion", "", 0],
    ["Caustic Touch", "", 0],
    ["Chill Touch", "", 0],
    ["Claws Of Darkness", "", 0],
    ["Clockwork Bolt", "", 0],
    ["Clumsiness", "", 0],
    ["Control Flames", "", 0],
    ["Create Bonfire", "", 0],
    ["Crushing Curse", "", 0],
    ["Dancing Lights", "", 0],
    ["Dark Maw", "", 0],
    ["Decay", "", 0],
    ["Douse Light", "", 0],
    ["Dragon Roar", "", 0],
    ["Druidcraft", "", 0],
    ["Eldritch Blast", "", 0],
    ["Encode Thoughts", "", 0],
    ["Encrypt / Decrypt", "Encrypt_Decrypt", 0],
    ["Enumerate", "", 0],
    ["Exceptional Wit", "", 0],
    ["Fire Bolt", "", 0],
    ["Fist Of Iron", "", 0],
    ["Fortitude", "", 0],
    ["Frailty", "", 0],
    ["Friends", "", 0],
    ["Frostbite", "", 0],
    ["Green-Flame Blade", "", 0],
    ["Guidance", "", 0],
    ["Gust", "", 0],
    ["Gust (Eberron)", "Gust", 0],
    ["Gust Barrier", "Gust", 0],
    ["Hamstring", "", 0],
    ["Hand Of Doom", "", 0],
    ["Hoarfrost", "", 0],
    ["Hobble", "", 0],
    ["Impotence", "", 0],
    ["Infestation", "", 0],
    ["Iron Hand", "", 0],
    ["Lesser Charm", "", 0],
    ["Light", "", 0],
    ["Lightning Lure", "", 0],
    ["Mage Hand", "", 0],
    ["Magic Stone", "", 0],
    ["Memento Mori", "", 0],
    ["Mending", "", 0],
    ["Message", "", 0],
    ["Mind Sliver", "", 0],
    ["Minor Illusion", "", 0],
    ["Misstep", "", 0],
    ["Mold Earth", "", 0],
    ["Nimbleness", "", 0],
    ["Obtuse", "", 0],
    ["Poison Spray", "", 0],
    ["Prestidigitation", "", 0],
    ["Primal Savagery", "", 0],
    ["Produce Flame", "", 0],
    ["Puff Of Smoke", "", 0],
    ["Pummelstone", "", 0],
    ["Quicken", "", 0],
    ["Ray of Frost", "", 0],
    ["Resistance", "", 0],
    ["Sacred Flame", "", 0],
    ["Sapping Sting", "", 0],
    ["Scribe", "", 0],
    ["Semblance Of Dread", "", 0],
    ["Shadow Bite", "", 0],
    ["Shadow Blindness", "", 0],
    ["Shape Water", "", 0],
    ["Shillelagh", "", 0],
    ["Shiver", "", 0],
    ["Shocking Grasp", "", 0],
    ["Silhouette", "", 0],
    ["Spare the Dying", "", 0],
    ["Starburst", "", 0],
    ["Sword Burst", "", 0],
    ["Telekinetic Trip", "", 0],
    ["Thaumaturgy", "", 0],
    ["Thorn Whip", "", 0],
    ["Thunder Bolt", "", 0],
    ["Thunderclap", "", 0],
    ["Toll the Dead", "", 0],
    ["Tree Heal", "", 0],
    ["True Strike", "", 0],
    ["Uncanny Avoidance", "", 0],
    ["Vicious Mockery", "", 0],
    ["Wind Lash", "", 0],
    ["Word Of Misfortune", "", 0],
    ["Word of Radiance", "", 0],
    ["Adjust Position", "", 1],
    ["Agonizing Mark", "", 1],
    ["Alarm", "", 1],
    ["Alter Arrow's Fortune", "Alter_Arrow_Fortune", 1],
    ["Amplify Light", "", 1],
    ["Analyze Device", "", 1],
    ["Ancestor's Strength", "Ancestor_Strength", 1],
    ["Anchoring Rope", "", 1],
    ["Angelic Guardian", "", 1],
    ["Animal Friendship", "", 1],
    ["Anticipate Weakness", "", 1],
    ["Armor of Agathys", "", 1],
    ["Arms of Hadar", "", 1],
    ["Auspicious Warning", "", 1],
    ["Avoid Grievous Injury", "", 1],
    ["Bane", "", 1],
    ["Beast Bond", "", 1],
    ["Black Ribbons", "", 1],
    ["Bleed", "", 1],
    ["Bless", "", 1],
    ["Blinding Pain", "", 1],
    ["Blood Scarab", "", 1],
    ["Bloodhound", "", 1],
    ["Bloody Hands", "", 1],
    ["Bloody Smite", "", 1],
    ["Bolster Undead", "", 1],
    ["Bottomless Stomach", "", 1],
    ["Breathtaking Wind", "", 1],
    ["Brimstone", "", 1],
    ["Broken Charge", "", 1],
    ["Burning Hands", "", 1],
    ["Candle's Insight", "Candle_Insight", 1],
    ["Catapult", "", 1],
    ["Cause Fear", "", 1],
    ["Ceremony", "", 1],
    ["Chaos Bolt", "", 1],
    ["Chaos Bolt (Ravnica)", "Chaos_Bolt", 1],
    ["Charm Of Long Standing", "", 1],
    ["Charm Person", "", 1],
    ["Chromatic Orb", "", 1],
    ["Chronal Lance", "", 1],
    ["Circle Of Wind", "", 1],
    ["Cloak Of Shadow", "", 1],
    ["Cobra Fangs", "", 1],
    ["Color Spray", "", 1],
    ["Command", "", 1],
    ["Compelled Duel", "", 1],
    ["Comprehend Languages", "", 1],
    ["Conjure Mock Animals", "", 1],
    ["Converse With Dragon", "", 1],
    ["Create or Destroy Water", "", 1],
    ["Cure Beast", "", 1],
    ["Cure Wounds", "", 1],
    ["Deep Breath", "", 1],
    ["Detect Evil and Good", "", 1],
    ["Detect Magic", "", 1],
    ["Detect Poison and Disease", "", 1],
    ["Disguise Self", "", 1],
    ["Disquieting Gaze", "", 1],
    ["Dissonant Whispers", "", 1],
    ["Divine Favor", "", 1],
    ["Doom Of The Cracked Shield", "", 1],
    ["Draconic Smite", "", 1],
    ["Earth Tremor", "", 1],
    ["Earworm Melody", "", 1],
    ["Ensnaring Strike", "", 1],
    ["Entangle", "", 1],
    ["Expeditious Retreat", "", 1],
    ["Extract Essence", "", 1],
    ["Faerie Fire", "", 1],
    ["False Life", "", 1],
    ["Feather Fall", "", 1],
    ["Feather Field", "", 1],
    ["Fey Glamer", "", 1],
    ["Find Familiar", "", 1],
    ["Find Kin", "", 1],
    ["Fire Under The Tongue", "", 1],
    ["Flurry", "", 1],
    ["Fog Cloud", "", 1],
    ["Forest Affinity", "", 1],
    ["Forest Native", "", 1],
    ["Foretell Distraction", "", 1],
    ["Freeze Potion", "", 1],
    ["Gift of Alacrity", "", 1],
    ["Gird the Spirit", "", 1],
    ["Glamer Of Mundanity", "", 1],
    ["Gliding Step", "", 1],
    ["Goat's Hoof Charm", "Goat_Hoof_Charm", 1],
    ["Goodberry", "", 1],
    ["Gordolay's Pleasant Aroma", "Gordolay_Pleasant_Aroma", 1],
    ["Grease", "", 1],
    ["Green Mantle", "", 1],
    ["Grim Siphon", "", 1],
    ["Guest Of Honor", "", 1],
    ["Guiding Bolt", "", 1],
    ["Guiding Star", "", 1],
    ["Hail of Thorns", "", 1],
    ["Hard Heart", "", 1],
    ["Healing Word", "", 1],
    ["Heart to Heart", "", 1],
    ["Hellish Rebuke", "", 1],
    ["Heroism", "", 1],
    ["Hex", "", 1],
    ["Hobble Mount", "", 1],
    ["Hone Blade", "", 1],
    ["Hunter's Endurance", "Hunter_Endurance", 1],
    ["Hunter's Mark", "Hunter_Mark", 1],
    ["Ice Knife", "", 1],
    ["Icicle Daggers", "", 1],
    ["Identify", "", 1],
    ["Ill-Fated Word", "", 1],
    ["Illuminate Spoor", "", 1],
    ["Illusory Script", "", 1],
    ["Inflict Wounds", "", 1],
    ["Insightful Maneuver", "", 1],
    ["Jump", "", 1],
    ["Kareef's Entreaty", "Kareef_Entreaty", 1],
    ["Kobold's Fury", "Kobold_Fury", 1],
    ["Liar's Gift", "Liar_Gift", 1],
    ["Life Transference Arrow", "", 1],
    ["Litany Of Sure Hands", "", 1],
    ["Longstrider", "", 1],
    ["Mage Armor", "", 1],
    ["Magic Missile", "", 1],
    ["Magnify Gravity", "", 1],
    ["Mammon's Avarice", "Mammon_Avarice", 1],
    ["Maw of Needles", "", 1],
    ["Mosquito Bane", "", 1],
    ["Mud Pack", "", 1],
    ["Nature's Aegis", "Nature_Aegis", 1],
    ["Nourishing Repast", "", 1],
    ["Pendulum", "", 1],
    ["Proselytize", "", 1],
    ["Protection From The Void", "", 1],
    ["Protection from Evil and Good", "", 1],
    ["Purify Food and Drink", "", 1],
    ["Ray of Sickness", "", 1],
    ["Ring Strike", "", 1],
    ["Roaming Pain", "", 1],
    ["Sanctuary", "", 1],
    ["Scentless", "", 1],
    ["Screaming Ray", "", 1],
    ["Searing Smite", "", 1],
    ["Seer's Reaction", "Seer_Reaction", 1],
    ["Shadow Armor", "", 1],
    ["Shadow Hands", "", 1],
    ["Shield", "", 1],
    ["Shield of Faith", "", 1],
    ["Silent Image", "", 1],
    ["Sleep", "", 1],
    ["Slippery Fingers", "", 1],
    ["Snare", "", 1],
    ["Snowy Coat", "", 1],
    ["Speak With Inanimate Object", "", 1],
    ["Speak with Animals", "Speak_With_Animals", 1],
    ["Spur Mount", "", 1],
    ["Stanch", "", 1],
    ["Step Like Me", "", 1],
    ["Strength Of An Ox", "", 1],
    ["Tasha's Caustic Brew", "Tasha_Caustic_Brew", 1],
    ["Tasha's Hideous Laughter", "Tasha_Hideous_Laughter", 1],
    ["Telekinetic Parry", "", 1],
    ["Tenser's Floating Disk", "Tenser_Floating_Disk", 1],
    ["Thin The Ice", "", 1],
    ["Thunderous Charge", "", 1],
    ["Thunderous Smite", "", 1],
    ["Thunderwave", "", 1],
    ["Tidal Barrier", "", 1],
    ["Tireless", "", 1],
    ["Treasure Chasm", "", 1],
    ["Tree Speak", "", 1],
    ["Trick Question", "", 1],
    ["Twist The Skein", "", 1],
    ["Undermine Armor", "", 1],
    ["Unluck On That", "", 1],
    ["Unruly Item", "", 1],
    ["Unseen Servant", "", 1],
    ["Voorish Sign", "", 1],
    ["Waft", "", 1],
    ["Weapon Of Blood", "", 1],
    ["Wind Tunnel", "", 1],
    ["Witch Bolt", "", 1],
    ["Withered Sight", "", 1],
    ["Withering Smite", "", 1],
    ["Wolfsong", "", 1],
    ["Wrathful Smite", "", 1],
    ["Writhing Arms", "", 1],
    ["Zephyr Strike", "", 1],
    ["Aganazzar's Scorcher", "Aganazzar_Scorcher", 2],
    ["Aid", "", 2],
    ["Alter Self", "", 2],
    ["Althea's Travel Tent", "Althea_Travel_Tent", 2],
    ["Animal Messenger", "", 2],
    ["Animal Spy", "", 2],
    ["Animate Ghoul", "", 2],
    ["Anticipate Attack", "", 2],
    ["Arcane Lock", "", 2],
    ["As You Were", "", 2],
    ["Ashen Memories", "", 2],
    ["Aspect Of The Ape", "", 2],
    ["Aspect Of The Ram", "", 2],
    ["Augury", "", 2],
    ["Bad Timing", "", 2],
    ["Barkskin", "", 2],
    ["Batsense", "", 2],
    ["Beast Sense", "", 2],
    ["Bedazzling Charm", "", 2],
    ["Beguiling Bet", "", 2],
    ["Bestial Fury", "", 2],
    ["Bitter Chains", "", 2],
    ["Black Swan Storm", "", 2],
    ["Bleating Call", "", 2],
    ["Blessed Halo", "", 2],
    ["Blessed Rest", "", 2],
    ["Blindness Deafness", "", 2],
    ["Blood Lure", "", 2],
    ["Bloodshot", "", 2],
    ["Blur", "", 2],
    ["Boiling Oil", "", 2],
    ["Boreas's Breath", "Boreas_Breath", 2],
    ["Boulder Toss", "", 2],
    ["Branding Smite", "", 2],
    ["By The Light Of The Moon", "", 2],
    ["Call a Roggenwolf", "", 2],
    ["Calm Emotions", "", 2],
    ["Carmello-Volta's Irksome Preserves", "Carmell-Volta_Irksome_Preserves", 2],
    ["Caustic Blood", "", 2],
    ["Champion's Weapon", "Champion_Weapon", 2],
    ["Chaotic Vitality", "", 2],
    ["Charm Of Great Fondness", "", 2],
    ["Clearing The Field", "", 2],
    ["Cloak Of Fiendish Menace", "", 2],
    ["Cloud of Daggers", "", 2],
    ["Comprehend Wild Shape", "", 2],
    ["Conjure Mantelet", "", 2],
    ["Conjure Scarab Swarm", "", 2],
    ["Conjure Spectral Dead", "", 2],
    ["Continual Flame", "", 2],
    ["Convoluted Dictum", "", 2],
    ["Cordon of Arrows", "", 2],
    ["Creeping Ice", "", 2],
    ["Crown of Madness", "", 2],
    ["Crushing Trample", "", 2],
    ["Daggerhawk", "", 2],
    ["Dark Path", "", 2],
    ["Darkbolt", "", 2],
    ["Darkness", "", 2],
    ["Darkvision", "", 2],
    ["Dead Walking", "", 2],
    ["Decelerate", "", 2],
    ["Delay Potion", "", 2],
    ["Destructive Resonance", "", 2],
    ["Detect Dragons", "", 2],
    ["Detect Thoughts", "", 2],
    ["Discern Weakness", "", 2],
    ["Distracting Divination", "", 2],
    ["Distraction Cascade", "", 2],
    ["Dome Of Silence", "", 2],
    ["Doom Of Consuming Fire", "", 2],
    ["Doom Of The Slippery Rogue", "", 2],
    ["Dragon's Breath", "Dragon_s_Breath", 2],
    ["Dust Devil", "", 2],
    ["Earthbind", "", 2],
    ["Ectoplasm", "", 2],
    ["Elemental Horns", "", 2],
    ["Elemental Twist", "", 2],
    ["Enhance Ability", "", 2],
    ["Enhance Familiar", "", 2],
    ["Enhance Greed", "", 2],
    ["Enlarge Reduce", "", 2],
    ["Enthrall", "", 2],
    ["Entomb In Ice", "", 2],
    ["Exude Acid", "", 2],
    ["Feather Travel", "", 2],
    ["Find Steed", "", 2],
    ["Find Traps", "", 2],
    ["Fire Darts", "", 2],
    ["Flame Blade", "", 2],
    ["Flaming Sphere", "", 2],
    ["Fortune’s Favor", "Fortune_Favor", 2],
    ["Frenzied Bolt", "", 2],
    ["Furious Hooves", "", 2],
    ["Gear Barrage", "", 2],
    ["Gentle Repose", "", 2],
    ["Gift Of Luck", "", 2],
    ["Gift Of Resilience", "", 2],
    ["Glyph Of Shifting", "", 2],
    ["Grain Of Truth", "", 2],
    ["Grave Sense", "", 2],
    ["Greater Analyze Device", "", 2],
    ["Grudge Match", "", 2],
    ["Gust of Wind", "", 2],
    ["Healing Spirit", "", 2],
    ["Heartache", "", 2],
    ["Heartstop", "", 2],
    ["Heartstrike", "", 2],
    ["Heat Metal", "", 2],
    ["Hold Person", "", 2],
    ["Holy Warding", "", 2],
    ["Hunter's Cunning", "Hunter_Cunning", 2],
    ["Hypnotic Missive", "Hypnotic_Missive", 2],
    ["Ice Hammer", "", 2],
    ["Immovable Object", "", 2],
    ["Indecision", "", 2],
    ["Instant Snare", "", 2],
    ["Invisibility", "", 2],
    ["Iron Stomach", "", 2],
    ["Jerilyn's Cadaverous Uprising", "Jerilyn_Cadeverous_Uprising", 2],
    ["Kavelin's Instant Aerosol", "Kavelin_Instant_Aerosol", 2],
    ["Knock", "", 2],
    ["Lacerate", "", 2],
    ["Lair Sense", "", 2],
    ["Lesser Restoration", "", 2],
    ["Levitate", "", 2],
    ["Locate Animals or Plants", "", 2],
    ["Locate Object", "", 2],
    ["Lock Armor", "", 2],
    ["Maddening Whispers", "", 2],
    ["Magic Mouth", "", 2],
    ["Magic Weapon", "", 2],
    ["Magma Spray", "", 2],
    ["Mantle Of The Brave", "", 2],
    ["Mark Prey", "", 2],
    ["Maximillian's Earthen Grasp", "Maximillian_Earthen_Grasp", 2],
    ["Melf's Acid Arrow", "Melf_Acid_Arrow", 2],
    ["Mephitic Croak", "", 2],
    ["Mind Spike", "", 2],
    ["Mirror Image", "", 2],
    ["Mist Of Wonders", "", 2],
    ["Misty Step", "", 2],
    ["Moonbeam", "", 2],
    ["Nathair's Mischief", "Nathair_Mischief", 2],
    ["Negative Image", "", 2],
    ["Nip at the Heels", "", 2],
    ["Nystul's Magic Aura", "Nystul_Magic_Aura", 2],
    ["Orb Of Light", "", 2],
    ["Pass without Trace", "", 2],
    ["Phantasmal Force", "", 2],
    ["Phantom Light", "", 2],
    ["Plaguebearer", "", 2],
    ["Poisoned Volley", "", 2],
    ["Poisonous Flesh", "", 2],
    ["Power Word Kneel", "", 2],
    ["Prayer Of Resolve", "", 2],
    ["Prayer of Healing", "", 2],
    ["Protection from Poison", "", 2],
    ["Pyrotechnics", "", 2],
    ["Silverquill’s Silvery Barbs ", "Silverquill_Silvery_Barbs", 2],
    ["Ray of Enfeeblement", "", 2],
    ["Read Object", "", 2],
    ["Reverberate", "", 2],
    ["Revive Beast", "", 2],
    ["Rime's Binding Ice", "Rime_Binding_Ice", 2],
    ["Rolling Thunder", "", 2],
    ["Rope Trick", "", 2],
    ["Rotting Corpse", "", 2],
    ["Scorching Ray", "", 2],
    ["Sculpt Snow", "", 2],
    ["See Invisibility", "", 2],
    ["Shade", "", 2],
    ["Shadow Blade", "", 2],
    ["Shadow Puppets", "", 2],
    ["Shadows Brought To Light", "", 2],
    ["Shared Sacrifice", "", 2],
    ["Shatter", "", 2],
    ["Sheen Of Ice", "", 2],
    ["Shifting The Odds", "", 2],
    ["Silence", "", 2],
    ["Skywrite", "", 2],
    ["Slither", "", 2],
    ["Snap the Leash", "", 2],
    ["Snilloc's Snowball Swarm", "Snilloc_Snowball_Swarm", 2],
    ["Snow Fort", "", 2],
    ["Solitary Fireball", "", 2],
    ["Spider Climb", "", 2],
    ["Spike Growth", "", 2],
    ["Spin", "", 2],
    ["Spiritual Weapon", "", 2],
    ["Spy My Shadow", "", 2],
    ["Stench of Rot", "", 2],
    ["Suggestion", "", 2],
    ["Summon Beast", "", 2],
    ["Tasha's Mind Whip", "Tasha_Mind_Whip", 2],
    ["Thorn Cage", "", 2],
    ["Thunderous Stampede", "", 2],
    ["Time Step", "", 2],
    ["Timely Distraction", "", 2],
    ["Tree Running", "", 2],
    ["Trench", "", 2],
    ["Unholy Defiance", "", 2],
    ["Vine Trestle", "", 2],
    ["Vomit Tentacles", "", 2],
    ["Warding Bond", "", 2],
    ["Warding Wind", "", 2],
    ["Warning Shout", "", 2],
    ["Web", "", 2],
    ["Weiler's Ward", "Weiler_Ward", 2],
    ["Wresting Wind", "", 2],
    ["Wristpocket", "", 2],
    ["Zone of Truth", "", 2],
    ["Accelerate", "", 3],
    ["Alone", "", 3],
    ["Animate Dead", "", 3],
    ["Anticipate Arcana", "", 3],
    ["Ashardalon's Stride", "Ashardalon_Stride", 3],
    ["Aspect Of The Serpent", "", 3],
    ["Aura Of Listlessness", "", 3],
    ["Aura Of Protection Or Destruction", "", 3],
    ["Aura of Vitality", "", 3],
    ["Beacon of Hope", "", 3],
    ["Bestow Curse", "", 3],
    ["Blade Of Wrath", "", 3],
    ["Blinding Smite", "", 3],
    ["Blink", "", 3],
    ["Blood Armor", "", 3],
    ["Blood Offering", "", 3],
    ["Bolstering Brew", "", 3],
    ["Bones Of Stone", "", 3],
    ["Booster Shot", "", 3],
    ["Breeze Compass", "", 3],
    ["Call Lightning", "", 3],
    ["Call Shadow Mastiff", "", 3],
    ["Calm Of The Storm", "", 3],
    ["Catch The Breath", "", 3],
    ["Catnap", "", 3],
    ["Chains Of Perdition", "", 3],
    ["Chilling Words", "", 3],
    ["Clairvoyance", "", 3],
    ["Cloak Of Vermin", "", 3],
    ["Closing In", "", 3],
    ["Command Undead", "", 3],
    ["Compelled Movement", "", 3],
    ["Compelling Fate", "", 3],
    ["Confound Senses", "", 3],
    ["Conjure Animals", "", 3],
    ["Conjure Barrage", "", 3],
    ["Conjure Undead", "", 3],
    ["Counterspell", "", 3],
    ["Create Food and Water", "", 3],
    ["Crusader's Mantle", "Crusader_Mantle", 3],
    ["Curse Of Hostility", "", 3],
    ["Curse Of Incompetence", "", 3],
    ["Cynophobia", "", 3],
    ["Dark Heraldry", "", 3],
    ["Daylight", "", 3],
    ["Deep Focus", "", 3],
    ["Defensive Quills", "", 3],
    ["Delayed Healing", "", 3],
    ["Demon Within", "", 3],
    ["Dimensional Shove", "", 3],
    ["Dispel Magic", "", 3],
    ["Doom Of Blue Crystal", "", 3],
    ["Doom Of Dancing Blades", "", 3],
    ["Doom Of Disenchantment", "", 3],
    ["Draconic Majesty", "", 3],
    ["Dragon's Pride", "Dragon_Pride", 3],
    ["Drown", "", 3],
    ["Dryad's Kiss", "Dryad_Kiss", 3],
    ["Ears Of The Bat", "", 3],
    ["Elemental Weapon", "", 3],
    ["Enemies Abound", "", 3],
    ["Entropic Damage Field", "", 3],
    ["Erupting Earth", "", 3],
    ["Fear", "", 3],
    ["Feign Death", "", 3],
    ["Fireball", "", 3],
    ["Flame Arrows", "", 3],
    ["Flesh To Paper", "", 3],
    ["Fly", "", 3],
    ["Forceful Repurposing", "", 3],
    ["Freeze Blood", "", 3],
    ["Freezing Fog", "", 3],
    ["Frostbitten Fingers", "", 3],
    ["Frozen Razors", "", 3],
    ["Gaseous Form", "", 3],
    ["Glimpse The End", "", 3],
    ["Gloomwrought Barrier", "", 3],
    ["Gluey Globule", "", 3],
    ["Glyph of Warding", "", 3],
    ["Going in Circles", "", 3],
    ["Haste", "", 3],
    ["Hedren's Birds Of Clay", "Hedren_Birds_Of_Clay", 3],
    ["Hellfire Blitz", "", 3],
    ["Hematomancy", "", 3],
    ["Hero's Steel", "Hero_Steel", 3],
    ["Holy Vow", "", 3],
    ["Hunger of Hadar", "", 3],
    ["Hypnotic Pattern", "", 3],
    ["Ice Burn", "", 3],
    ["Illusory Trap", "", 3],
    ["Impending Ally", "", 3],
    ["Innocuous Aspect", "", 3],
    ["Intellect Fortress", "", 3],
    ["Invested Champion", "", 3],
    ["Ire of the Mountain", "", 3],
    ["Iron Mind", "", 3],
    ["Jeweled Fissure", "", 3],
    ["Lance Of The Sun God", "", 3],
    ["Laugh In The Face Of Fear", "", 3],
    ["Legion", "", 3],
    ["Legion of Rabid Squirrels", "", 3],
    ["Leomund's Tiny Hut", "Leomund_Tiny_Hut", 3],
    ["Lesser Maze", "", 3],
    ["Life Sense", "", 3],
    ["Life Transference", "", 3],
    ["Life from Death", "", 3],
    ["Lightning Arrow", "", 3],
    ["Lightning Bolt", "", 3],
    ["Magic Circle", "", 3],
    ["Major Image", "", 3],
    ["Mass Healing Word", "", 3],
    ["Mass Hobble Mount", "", 3],
    ["Meld into Stone", "", 3],
    ["Melf's Minute Meteors", "Melf_Minute_Meteors", 3],
    ["Mind Exchange", "", 3],
    ["Mire", "", 3],
    ["Monstrous Empathy", "", 3],
    ["Mortal Insight", "", 3],
    ["Nest Of Infernal Vipers", "", 3],
    ["Nightfall", "", 3],
    ["Nondetection", "", 3],
    ["Opportunistic Foresight", "", 3],
    ["Outflanking Boon", "", 3],
    ["Phantom Dragon", "", 3],
    ["Phantom Steed", "", 3],
    ["Phase Bolt", "", 3],
    ["Plant Growth", "", 3],
    ["Portal Jaunt", "", 3],
    ["Potency Of The Pack", "", 3],
    ["Protection from Energy", "", 3],
    ["Protective Ice", "", 3],
    ["Protective Nimbus", "", 3],
    ["Pulse Wave", "", 3],
    ["Quench", "", 3],
    ["Raise Ghost", "", 3],
    ["Reaver Spirit", "", 3],
    ["Remove Curse", "", 3],
    ["Remove Scent", "", 3],
    ["Revivify", "", 3],
    ["Riptide", "", 3],
    ["Rune Of Imprisonment", "", 3],
    ["Salt Lash", "", 3],
    ["Seeping Death", "", 3],
    ["Sending", "", 3],
    ["Shadow Tendrils", "", 3],
    ["Shadow Trove", "", 3],
    ["Shield Of Starlight", "", 3],
    ["Sidestep Arrow", "", 3],
    ["Sir Mittinz's Move Curse", "Sir_mittinz_move_curse", 3],
    ["Sleep Of The Deep", "", 3],
    ["Sleet Storm", "", 3],
    ["Slow", "", 3],
    ["Slow-Burn Fireball", "", 3],
    ["Song Of The Forest", "", 3],
    ["Soothing Chant", "", 3],
    ["Soul Borrowing", "", 3],
    ["Speak with Dead", "", 3],
    ["Speak with Plants", "", 3],
    ["Spirit Guardians", "", 3],
    ["Spirit Shroud", "", 3],
    ["Spiteful Weapon", "", 3],
    ["Steal Warmth", "", 3],
    ["Sting Of The Scorpion Goddess", "", 3],
    ["Stinking Cloud", "", 3],
    ["Storm God's Doom", "Storm_God_Doom", 3],
    ["Sudden Dawn", "", 3],
    ["Summon Fey", "", 3],
    ["Summon Lesser Demons", "", 3],
    ["Summon Shadowspawn", "", 3],
    ["Summon Undead", "", 3],
    ["Surge Dampener", "", 3],
    ["Targeting Foreknowledge", "", 3],
    ["Terrifying Lash", "", 3],
    ["Thousand Darts", "", 3],
    ["Throes Of Ecstasy", "", 3],
    ["Thunder Step", "", 3],
    ["Thunderous Wave", "", 3],
    ["Tidal Wave", "", 3],
    ["Tiny Servant", "", 3],
    ["Tongue Of Sand", "", 3],
    ["Tongues", "", 3],
    ["Touch of the Unliving", "", 3],
    ["Tracer", "", 3],
    ["Tracking Beacon", "", 3],
    ["Unseen Strangler", "", 3],
    ["Vampiric Touch", "", 3],
    ["Vital Mark", "", 3],
    ["Void Strike", "", 3],
    ["Wall of Sand", "", 3],
    ["Wall of Water", "", 3],
    ["Water Breathing", "", 3],
    ["Water Walk", "", 3],
    ["Wave Of Corruption", "", 3],
    ["Wind Wall", "", 3],
    ["Arcane Eye", "", 4],
    ["Aura Of Entropy", "", 4],
    ["Aura of Life", "", 4],
    ["Aura of Purity", "", 4],
    ["Banishment", "", 4],
    ["Binding Oath", "", 4],
    ["Black Hand", "", 4],
    ["Blade Of My Brother", "", 4],
    ["Blight", "", 4],
    ["Blood And Steel", "", 4],
    ["Blood Puppet", "", 4],
    ["Blood Spoor", "", 4],
    ["Boiling Blood", "", 4],
    ["Brittling", "", 4],
    ["By The Light Of The Watchful Moon", "", 4],
    ["Caustic Waste", "", 4],
    ["Chains Of Torment", "", 4],
    ["Chaotic Form", "", 4],
    ["Charm Monster", "", 4],
    ["Cherub's Burning Blade", "Cherub_Burning_Blade", 4],
    ["Cloak Of Serpents", "", 4],
    ["Compulsion", "", 4],
    ["Confusion", "", 4],
    ["Conjure Fiends", "", 4],
    ["Conjure Minor Elementals", "", 4],
    ["Conjure Woodland Beings", "", 4],
    ["Consult The Storm", "", 4],
    ["Control Water", "", 4],
    ["Cursed Gift", "", 4],
    ["Death Ward", "", 4],
    ["Deep Freeze", "", 4],
    ["Desiccating Breath", "", 4],
    ["Deva's Wings", "Deva_Wings", 4],
    ["Dimension Door", "", 4],
    ["Distressing Resonance", "", 4],
    ["Divination", "", 4],
    ["Dominate Beast", "", 4],
    ["Doom Of Serpent Coils", "", 4],
    ["Doom Of The Earthen Maw", "", 4],
    ["Doom Of The Pit", "", 4],
    ["Draconic Senses", "", 4],
    ["Drain Item", "", 4],
    ["Dread Wings", "", 4],
    ["Earthskimmer", "", 4],
    ["Echoes Of Steel", "", 4],
    ["Elemental Bane", "", 4],
    ["Emanation Of Yoth", "", 4],
    ["Endow Attribute", "", 4],
    ["Energy Foreknowledge", "", 4],
    ["Evard's Black Tentacles", "Evard_Black_Tentacles", 4],
    ["Evercold", "", 4],
    ["Fabricate", "", 4],
    ["Find Greater Steed", "", 4],
    ["Fire Shield", "", 4],
    ["Flame Wave", "", 4],
    ["Flickering Fate", "", 4],
    ["Fluctuating Alignment", "", 4],
    ["Fog Of War", "", 4],
    ["Freedom of Movement", "", 4],
    ["Fusillade Of Ice", "", 4],
    ["Giant Insect", "", 4],
    ["Giant's Jest", "Giant_Jest", 4],
    ["Grasping Vine", "", 4],
    ["Gravity Sinkhole", "", 4],
    ["Greater Invisibility", "", 4],
    ["Green Decay", "", 4],
    ["Guardian of Faith", "", 4],
    ["Guardian of Nature", "", 4],
    ["Hallucinatory Terrain", "", 4],
    ["Harry", "", 4],
    ["Heart-Seeking Arrow", "", 4],
    ["Hide In One's Shadow", "Hide_In_One_Shadow", 4],
    ["Hunger Of Leng", "", 4],
    ["Hunting Stand", "", 4],
    ["Ice Storm", "", 4],
    ["Inspiring Speech", "", 4],
    ["Instant Siege Weapon", "", 4],
    ["Keening Wail", "", 4],
    ["Labyrinth Mastery", "", 4],
    ["Lava Stone", "", 4],
    ["Leomund's Secret Chest", "Leomund_Secret_Chest", 4],
    ["Locate Creature", "", 4],
    ["Looping Trail", "", 4],
    ["Lovesick", "", 4],
    ["Moon Trap", "", 4],
    ["Mordenkainen's Faithful Hound", "Mordenkainen_Faithful_Hound", 4],
    ["Mordenkainen's Private Sanctum", "Mordenkainen_Private_Sanctum", 4],
    ["Nether Weapon", "", 4],
    ["Night Terrors", "", 4],
    ["Not Dead Yet", "", 4],
    ["Otiluke's Resilient Sphere", "Otiluke_Resilient_Sphere", 4],
    ["Overwhelming Greed", "", 4],
    ["Phantasmal Killer", "", 4],
    ["Pitfall", "", 4],
    ["Polymorph", "", 4],
    ["Power Word Pain", "", 4],
    ["Quick Time", "", 4],
    ["Quicksilver Mantle", "", 4],
    ["Raid The Lair", "", 4],
    ["Raise Hero", "", 4],
    ["Raise Shade", "", 4],
    ["Raulothim's Psychic Lance", "Raulothim_Psychic_Lance", 4],
    ["Ray Of Alchemical Negation", "", 4],
    ["Ray Of Life Suppression", "", 4],
    ["Reposition", "", 4],
    ["Reset", "", 4],
    ["Sacrificial Healing", "", 4],
    ["Sand Ship", "", 4],
    ["Scale Rot", "", 4],
    ["Scaly Hide", "", 4],
    ["Scry Ambush", "", 4],
    ["Searing Sun", "", 4],
    ["Servant Of Doom", "", 4],
    ["Shadow Monsters", "", 4],
    ["Shadow Step", "", 4],
    ["Shadow of Moil", "", 4],
    ["Shadowy Retribution", "", 4],
    ["Shocking Shroud", "", 4],
    ["Shroud Of Death", "", 4],
    ["Sickening Radiance", "", 4],
    ["Snow Boulder", "", 4],
    ["Spectral Herd", "", 4],
    ["Spinning Axes", "", 4],
    ["Staff Of Violet Fire", "", 4],
    ["Staggering Smite", "", 4],
    ["Steam Blast", "", 4],
    ["Stone Shape", "", 4],
    ["Stoneskin", "", 4],
    ["Storm Sphere", "", 4],
    ["Storm of Wings", "", 4],
    ["Sudden Stampede", "", 4],
    ["Summon Aberration", "", 4],
    ["Summon Construct", "", 4],
    ["Summon Elemental", "", 4],
    ["Summon Greater Demon", "", 4],
    ["Time Vortex", "", 4],
    ["Tome Curse", "", 4],
    ["Torrent of Fire", "", 4],
    ["True Light Of Revelation", "", 4],
    ["Visage Of Madness", "", 4],
    ["Visage Of The Dead", "", 4],
    ["Vitriolic Sphere", "", 4],
    ["Wall of Fire", "", 4],
    ["Watery Sphere", "", 4],
    ["Wayward Strike", "", 4],
    ["Wild Shield", "", 4],
    ["Wintry Glide", "", 4],
    ["Yellow Sign", "", 4],
    ["Acid Rain", "", 5],
    ["Ancient Shade", "", 5],
    ["Animate Objects", "", 5],
    ["Animated Object Swarm", "", 5],
    ["Antilife Shell", "", 5],
    ["Awaken", "", 5],
    ["Babble", "", 5],
    ["Banishing Smite", "", 5],
    ["Battle Mind", "", 5],
    ["Bigby's Hand", "Bigby_Hand", 5],
    ["Blazing Chariot", "", 5],
    ["Bottled Arcana", "", 5],
    ["Chains Of The Goddess", "", 5],
    ["Channel Fiendish Power", "", 5],
    ["Circle of Power", "", 5],
    ["Clash Of Glaciers", "", 5],
    ["Claws Of The Earth Dragon", "", 5],
    ["Clockwork Bodyguard", "", 5],
    ["Cloudkill", "", 5],
    ["Commune", "", 5],
    ["Commune with Nature", "", 5],
    ["Cone of Cold", "", 5],
    ["Conjure Elemental", "", 5],
    ["Conjure Fey Hound", "", 5],
    ["Conjure Minor Voidborn", "", 5],
    ["Conjure Nightmare", "", 5],
    ["Conjure Volley", "", 5],
    ["Contact Other Plane", "", 5],
    ["Contagion", "", 5],
    ["Control Ice", "", 5],
    ["Control Winds", "", 5],
    ["Creation", "", 5],
    ["Cruor Of Visions", "", 5],
    ["Curse Of Yig", "", 5],
    ["Curse Ring", "", 5],
    ["Danse Macabre", "", 5],
    ["Dark Dementing", "", 5],
    ["Dark Lord's Mantle", "Dark_Lord_Mantle", 5],
    ["Dark Web Of The Spider Monarch", "", 5],
    ["Dawn", "", 5],
    ["Destructive Wave", "", 5],
    ["Detonate Corpses", "", 5],
    ["Dispel Evil and Good", "", 5],
    ["Dominate Person", "", 5],
    ["Dragon Breath", "", 5],
    ["Dream", "", 5],
    ["Earth Wave", "", 5],
    ["Eidetic Memory", "", 5],
    ["Eldritch Communion", "", 5],
    ["Energy Absorption", "", 5],
    ["Enervation", "", 5],
    ["Essence Instability", "", 5],
    ["Exsanguinate", "", 5],
    ["Exsanguinating Cloud", "", 5],
    ["Far Step", "", 5],
    ["Fey Crown", "", 5],
    ["Fiendish Brand", "", 5],
    ["Flame Strike", "", 5],
    ["Forest Of Spears", "", 5],
    ["Frostbite", "", 5],
    ["Geas", "", 5],
    ["Grasp Of The Tupilak", "", 5],
    ["Greater Protective Nimbus", "", 5],
    ["Greater Restoration", "", 5],
    ["Hallow", "", 5],
    ["Harrying Hounds", "", 5],
    ["Hold Monster", "", 5],
    ["Holy Ground", "", 5],
    ["Holy Weapon", "", 5],
    ["Ice Fortress", "", 5],
    ["Immolation", "", 5],
    ["Infernal Calling", "", 5],
    ["Insect Plague", "", 5],
    ["Instant Fortification", "", 5],
    ["Killing Fields", "", 5],
    ["Kiss Of The Succubus", "", 5],
    ["Labyrinthine Howl", "", 5],
    ["Lay to Rest", "", 5],
    ["Legend Lore", "", 5],
    ["Living Shadows", "", 5],
    ["Maelstrom", "", 5],
    ["Magnetize", "", 5],
    ["Maim", "", 5],
    ["Mass Cure Wounds", "", 5],
    ["Mass Surge Dampener", "", 5],
    ["Mislead", "", 5],
    ["Modify Memory", "", 5],
    ["Moonlight Charm", "", 5],
    ["Necrotic Leech", "", 5],
    ["Negative Energy Flood", "", 5],
    ["Not This Day!", "", 5],
    ["Passwall", "", 5],
    ["Planar Binding", "", 5],
    ["Primal Infusion", "", 5],
    ["Prismatic Ray", "", 5],
    ["Rain Of Blades", "", 5],
    ["Raise Dead", "", 5],
    ["Raise Nemesis", "", 5],
    ["Rary's Telepathic Bond", "Ray_Telepathic_Bond", 5],
    ["Recharge", "", 5],
    ["Reincarnate", "", 5],
    ["Sanguine Horror", "", 5],
    ["Scrying", "", 5],
    ["See Beyond", "", 5],
    ["Seeming", "", 5],
    ["Shadow Gateway", "", 5],
    ["Skill Empowerment", "", 5],
    ["Souleater", "", 5],
    ["Starfall", "", 5],
    ["Steel Wind Strike", "", 5],
    ["Summon Celestial", "", 5],
    ["Summon Draconic Spirit", "", 5],
    ["Summon Eldritch Servitor", "", 5],
    ["Sun's Bounty", "Sun_Bounty", 5],
    ["Surprise Blessing", "", 5],
    ["Swift Exchange", "", 5],
    ["Swift Quiver", "", 5],
    ["Synaptic Static", "", 5],
    ["Telekinesis", "", 5],
    ["Teleportation Circle", "", 5],
    ["Temporal Shunt", "", 5],
    ["Thunderstorm", "", 5],
    ["Tongue Tied", "", 5],
    ["Transmute Rock", "", 5],
    ["Tree Stride", "", 5],
    ["Wall Of Time", "", 5],
    ["Wall of Force", "", 5],
    ["Wall of Light", "", 5],
    ["Wall of Stone", "", 5],
    ["Wrath of Nature", "", 5],
    ["Absorbing Field", "", 6],
    ["Alchemical Form", "", 6],
    ["Ally Aegis", "", 6],
    ["Animate Greater Undead", "", 6],
    ["Arcane Gate", "", 6],
    ["Aspect Of The Firebird", "", 6],
    ["Aura Of Wrath", "", 6],
    ["Avronin's Astral Assembly", "Avronin_s_Astral_Assembly", 6],
    ["Become Nightwing", "", 6],
    ["Black Well", "", 6],
    ["Blade Barrier", "", 6],
    ["Bones of the Earth", "", 6],
    ["Bouncing Fireball", "", 6],
    ["Burning Radiance", "", 6],
    ["Catapult", "", 6],
    ["Cave Dragon's Dominance", "Cave_Dragon_s_Dominance", 6],
    ["Celestial Fanfare", "", 6],
    ["Chain Lightning", "", 6],
    ["Chaotic World", "", 6],
    ["Circle of Death", "", 6],
    ["Claim Lair", "", 6],
    ["Conjure Fey", "", 6],
    ["Conjure Forest Defender", "", 6],
    ["Contingency", "", 6],
    ["Create Homunculus", "", 6],
    ["Create Undead", "", 6],
    ["Curse Of Boreas", "", 6],
    ["Disintegrate", "", 6],
    ["Drawmij's Instant Summons", "Drawmij_s_Instant_Summons", 6],
    ["Druid Grove", "", 6],
    ["Enchant Ring", "", 6],
    ["Encroaching Shadows", "", 6],
    ["Entomb", "", 6],
    ["Extract Knowledge", "", 6],
    ["Eyebite", "", 6],
    ["Fault Line", "", 6],
    ["Find the Path", "", 6],
    ["Fire Dragon's Fury", "Fire_Dragon_s_Fury", 6],
    ["Firewalk", "", 6],
    ["Fizban's Platinum Shield", "Fizban_s_Platinum_Shield", 6],
    ["Flesh to Stone", "", 6],
    ["Forbiddance", "", 6],
    ["Globe of Invulnerability", "", 6],
    ["Gravity Fissure", "", 6],
    ["Guards and Wards", "", 6],
    ["Harm", "", 6],
    ["Heal", "", 6],
    ["Heavenly Crown", "", 6],
    ["Heroes' Feast", "", 6],
    ["Icy Manipulation", "", 6],
    ["Investiture Of Blight", "", 6],
    ["Investiture of Flame", "", 6],
    ["Investiture of Ice", "", 6],
    ["Investiture of Stone", "", 6],
    ["Investiture of Wind", "", 6],
    ["Life Drain", "", 6],
    ["Magic Jar", "", 6],
    ["Mass Suggestion", "", 6],
    ["Mental Prison", "", 6],
    ["Misfortune", "", 6],
    ["Mithral Dragon's Might", "Mithral_Dragon_s_Might", 6],
    ["Move Earth", "", 6],
    ["Otiluke's Freezing Sphere", "Otiluke_s_Freezing_Sphere", 6],
    ["Otto's Irresistible Dance", "Otto_s_Irresistible_Dance", 6],
    ["Planar Ally", "", 6],
    ["Primordial Ward", "", 6],
    ["Programmed Illusion", "", 6],
    ["Raise Elder", "", 6],
    ["Raise Questing Dead", "", 6],
    ["Scatter", "", 6],
    ["Shadow Metamorphosis", "", 6],
    ["Smiting Arrow", "", 6],
    ["Soul Cage", "", 6],
    ["Storm Form", "", 6],
    ["Summon Fiend", "", 6],
    ["Sunbeam", "", 6],
    ["Tasha's Otherworldly Guise", "Tasha_s_Otherworldly_Guise", 6],
    ["Tenser's Transformation", "Tenser_s_Transformation", 6],
    ["Time Loop", "", 6],
    ["Tolling Doom", "", 6],
    ["Transport via Plants", "", 6],
    ["True Seeing", "", 6],
    ["Walk The Twisted Path", "", 6],
    ["Wall of Ice", "", 6],
    ["Wall of Thorns", "", 6],
    ["Warp Mind And Matter", "", 6],
    ["Wind Walk", "", 6],
    ["Winter's Radiance", "", 6],
    ["Winterdark", "", 6],
    ["Word of Recall", "", 6],
    ["Acid Gate", "", 7],
    ["Alter Time Flow", "", 7],
    ["Amplify Gravity", "", 7],
    ["Arcane Parasite", "", 7],
    ["Aspect Of The Dragon", "", 7],
    ["Blizzard", "", 7],
    ["Celebration", "", 7],
    ["Conjure Celestial", "", 7],
    ["Conjure Greater Spectral Dead", "", 7],
    ["Conjure Shadow Titan", "", 7],
    ["Conjure Voidborn", "", 7],
    ["Create Thunderstaff", "", 7],
    ["Crown of Stars", "", 7],
    ["Curse Of Dust", "", 7],
    ["Curse Of The Grave", "", 7],
    ["Death God's Touch", "", 7],
    ["Defile Healing", "", 7],
    ["Delayed Blast Fireball", "", 7],
    ["Divine Word", "", 7],
    ["Draconic Transformation", "", 7],
    ["Dream of the Blue Veil", "", 7],
    ["Dying Of The Light", "", 7],
    ["Etherealness", "", 7],
    ["Finger of Death", "", 7],
    ["Fire Storm", "", 7],
    ["Forcecage", "", 7],
    ["Glacial Fog", "", 7],
    ["Ice Soldiers", "", 7],
    ["Icy Grasp Of The Void", "", 7],
    ["Last Rays Of The Dying Sun", "", 7],
    ["Legend Killer", "", 7],
    ["Mirage Arcane", "", 7],
    ["Mordenkainen's Magnificent Mansion", "Mordenkainen_s_Magnificent_Mansion", 7],
    ["Mordenkainen's Sword", "Mordenkainen_s_Sword", 7],
    ["Plane Shift", "", 7],
    ["Power Word Pain", "", 7],
    ["Prismatic Spray", "", 7],
    ["Project Image", "", 7],
    ["Ravages Of Time", "", 7],
    ["Regenerate", "", 7],
    ["Resurrection", "", 7],
    ["Reverse Gravity", "", 7],
    ["Right The Stars", "", 7],
    ["Ring Ward", "", 7],
    ["Seal Of Sanctuary", "", 7],
    ["Sequester", "", 7],
    ["Sign Of Koth", "", 7],
    ["Simulacrum", "", 7],
    ["Soothing Incandescence", "", 7],
    ["Starry Vision", "", 7],
    ["Symbol", "", 7],
    ["Symbol Of Sorcery", "", 7],
    ["Talons Of A Hungry Land", "", 7],
    ["Teleport", "", 7],
    ["Temple of the Gods", "", 7],
    ["Tether Essence", "", 7],
    ["Time Jaunt", "", 7],
    ["Transmogrification", "", 7],
    ["Triumph Of Ice", "", 7],
    ["Uncontrollable Transformation", "", 7],
    ["Volley Shield", "", 7],
    ["Walking Wall", "", 7],
    ["Whirlwind", "", 7],
    ["Wild Trajectory", "", 7],
    ["Animal Shapes", "", 8],
    ["Antimagic Field", "", 8],
    ["Antipathy Sympathy", "", 8],
    ["Arcane Sight", "", 8],
    ["Awaken Object", "", 8],
    ["Black Sunshine", "", 8],
    ["Bloom", "", 8],
    ["Caustic Torrent", "", 8],
    ["Clone", "", 8],
    ["Control Weather", "", 8],
    ["Costly Victory", "", 8],
    ["Create Ring Servant", "", 8],
    ["Creeping Darkness", "", 8],
    ["Dark Star", "", 8],
    ["Deadly Sting", "", 8],
    ["Demiplane", "", 8],
    ["Desolation", "", 8],
    ["Disruptive Aura", "", 8],
    ["Dominate Monster", "", 8],
    ["Earthquake", "", 8],
    ["Feeblemind", "", 8],
    ["Frailform", "", 8],
    ["Ghoul King's Cloak", "Ghoul_King_s_Cloak", 8],
    ["Glacial Cascade", "", 8],
    ["Glibness", "", 8],
    ["Glimpse Of The Void", "", 8],
    ["Harsh Light Of Summer's Glare", "Harsh_Light_Of_Summer_s_Glare",8],
    ["Holy Aura", "", 8],
    ["Illusory Dragon", "", 8],
    ["Incendiary Cloud", "", 8],
    ["Life Hack", "", 8],
    ["Lower The Veil", "", 8],
    ["Maddening Darkness", "", 8],
    ["Malevolent Waves", "", 8],
    ["Maze", "", 8],
    ["Mighty Fortress", "", 8],
    ["Mind Blank", "", 8],
    ["Paragon Of Chaos", "", 8],
    ["Power Word Stun", "", 8],
    ["Quintessence", "", 8],
    ["Reality Break", "", 8],
    ["Roaring Winds Of Limbo", "", 8],
    ["Seed Of Destruction", "", 8],
    ["Steam Whistle", "", 8],
    ["Summon Star", "", 8],
    ["Sunburst", "", 8],
    ["Telepathy", "", 8],
    ["Time Jump", "", 8],
    ["Time Slippage", "", 8],
    ["Tsunami", "", 8],
    ["Wind Of The Hereafter", "", 8],
    ["Afflict Line", "", 9],
    ["Astral Projection", "", 9],
    ["Black Hole", "", 9],
    ["Blade of Disaster", "", 9],
    ["Blood To Acid", "", 9],
    ["Circle Of Devastation", "", 9],
    ["Foresight", "", 9],
    ["Forest Sanctuary", "", 9],
    ["Form Of The Gods", "", 9],
    ["Gate", "", 9],
    ["Greater Maze", "", 9],
    ["Greater Seal Of Sanctuary", "", 9],
    ["Imprisonment", "", 9],
    ["Invulnerability", "", 9],
    ["Mammon's Due", "", 9],
    ["Mass Heal", "", 9],
    ["Mass Polymorph", "", 9],
    ["Meteor Swarm", "", 9],
    ["Power Word Heal", "", 9],
    ["Power Word Kill", "", 9],
    ["Prismatic Wall", "", 9],
    ["Psychic Scream", "", 9],
    ["Pyroclasm", "", 9],
    ["Ravenous Void", "", 9],
    ["Shapechange", "", 9],
    ["Star's Heart", "", 9],
    ["Storm of Vengeance", "", 9],
    ["Summon Avatar", "", 9],
    ["Time In A Bottle", "", 9],
    ["Time Ravage", "", 9],
    ["Time Stop", "", 9],
    ["True Polymorph", "", 9],
    ["True Resurrection", "", 9],
    ["Umbral Storm", "", 9],
    ["Unleash Effigy", "", 9],
    ["Unshackled Magic", "", 9],
    ["Void Rift", "", 9],
    ["Weird", "", 9],
    ["Wish", "", 9],
    ["Ambush Prey", "", 2],
    ["Elevated Sight", "", 1],
    ["Feathered Reach", "", 3],
    ["Globe of Twilight", "", 3],
    ["Invoke the Amaranthine", "", 3],
    ["Shape Plants", "", 4],
    ["Spiny Shield", "", 1],
    ["Stellar Bodies", "", 4],
    ["Veil of Dusk", "", 1]
];


